name: "emsdk_test"
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14

      - name: Verify
        run: emcc -v
      - name: Configure
        run: ./step1_configure.sh
