name: "emsdk_test"
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14

      - name: Verify
        run: emcc -v
      - name: Make the script files executable
        run: chmod +x step1_configure.sh step2_ffmpegwasm.sh configure ffbuild/*.sh
      - name: Configure and Make
        run: ./step1_configure.sh
      - name: Compile
        run: |
          mkdir out_dir
          bash step2_ffmpegwasm.sh -o out_dir/ffmpeg.js
      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: result_dir
          path: out_dir
